language: java
script: mvn clean package -P strict
after_success:
  - mvn jacoco:report coveralls:report
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
branches:
  only:
  - master
sudo: false
cache:
  directories:
    - $HOME/.m2
